In [1]:
import numpy as np
a=np.matrix([[1, 2], [4, -1]])
b=np.matrix([[1, 2], [4, 5,]])
print(a*b-b*a)


[[  0  12]
 [-24   0]]


In [2]:
import numpy as np
a=np.matrix([[-1, 2], [0, 1]])
b=a.dot(a)
print(b)

[[1 0]
 [0 1]]


In [3]:
import numpy as np
a=np.matrix([[3, 5], [6, -1]])
b=np.matrix([[2, 1], [-3, 2]])
c=a.dot(b)
print(c)

[[-9 13]
 [15  4]]


In [4]:
import numpy as np
a=np.matrix([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
aa=np.linalg.det(a)
print(aa)

35.00000000000001


In [5]:
import numpy as np
a=np.matrix([[1, 2, 3, 4], [-2, 1, -4, 3], [3, -4, -4, 2], [4, 3, -2, -1]])
aa=np.linalg.det(a)
print(aa)

990.0000000000001


In [6]:
import numpy as np
a=np.matrix([[1, 2, -3], [0, 1, 2], [0, 0, 1]])
aa=np.linalg.inv(a)
print(aa)

[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [7]:
import numpy as np
a=np.matrix([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
aa=np.linalg.matrix_rank(a)
print(aa)

2


In [8]:
import numpy as np
a=np.matrix('1 -4 0; 2 -3 1; 1 4 2')
b=np.matrix([[-5], [-7], [-1]])
print('a = ', a)
print('b = ', b)

def kramer(a,b):
    aa=np.linalg.det(a)
    print('Детермінація матриці', aa)
    if(aa!=0):
        print('Розвязування системи')
        x_m=np.matrix(a)
        x_m[:, 0]=b
        print('x_m = ', x_m)
        y_m=np.matrix(a)
        y_m[:, 0]=b
        print('y_m = ', y_m)
        z_m=np.matrix(a)
        z_m[:, 0]=b
        print('z_m = ', z_m)
        x=np.linalg.det(x_m)/aa
        y=np.linalg.det(y_m)/aa
        z=np.linalg.det(z_m)/aa
        print('x = ', round(x,5))
        print('y = ', round(y,5))
        print('z = ', round(z,5))
    else:
        print('Немає розвязків')
kramer(a,b)
x=np.linalg.solve(a,b)

print('Перевірка x = ', x)

a =  [[ 1 -4  0]
 [ 2 -3  1]
 [ 1  4  2]]
b =  [[-5]
 [-7]
 [-1]]
Детермінація матриці 2.000000000000001
Розвязування системи
x_m =  [[-5 -4  0]
 [-7 -3  1]
 [-1  4  2]]
y_m =  [[-5 -4  0]
 [-7 -3  1]
 [-1  4  2]]
z_m =  [[-5 -4  0]
 [-7 -3  1]
 [-1  4  2]]
x =  -1.0
y =  -1.0
z =  -1.0
Перевірка x =  [[-1.]
 [ 1.]
 [-2.]]
